baseURL = "https://bhagwadgita.info/"
languageCode = "en-us"
title = "श्रीमद् भगवद्गीता"
theme = "book"
publishDir = "docs"

[params]
	author = "baba"
	description = "Web based bhagwat geeta reader."
	bio = ""
	