//
//  FamousVerses.swift
//  Gita
//

import Foundation

/// The eighty verses most people arrive already knowing.
///
/// Eighty of 701 is a marker on one verse in nine, and `FamousVersesTests`
/// holds it under one in eight — seven entries of headroom, which is close
/// enough that the next addition should come with a deletion. The rarer the
/// ring, the more it says.
///
/// A property of the **text**, not of the reader — which is what keeps it out
/// of `user.sqlite` and out of `ReadingProgress`. Nothing here changes, nothing
/// is earned, and nothing is reset; it is the same list on a first launch as on
/// the thousandth, so it belongs beside the corpus as a constant.
///
/// Held here rather than as a column in `gita.sqlite` for one reason: the
/// database is generated by `tools/build_db.py` from `srimad.csv`, and this is
/// editorial judgement rather than scraped data. Putting it in the schema would
/// mean a rebuild of the bundled database — and a review of the generator — to
/// change one opinion about which verses are well known.
///
/// Chapter and verse rather than row id, because that is how the list is
/// discussed, quoted and checked; ids are an implementation detail of the
/// build and would silently rot if the corpus were ever renumbered.
/// `nonisolated` because `Verse` is: the models are `Sendable` structs that
/// cross the database boundary on whatever thread GRDB hands them over on, and
/// a constant they consult cannot be main-actor only. Nothing here is mutable,
/// so there is nothing to isolate.
nonisolated enum FamousVerses {
    /// One entry per verse, in reading order — not in order of fame, which is
    /// unrankable, and not in the order they were suggested, which is nobody's.
    static let all: Set<Reference> = [
        // Chapter 1
        Reference(1, 1),        // Dhrtarastra's question — the first line of the book.
        Reference(1, 28),       // Arjuna sees his own people drawn up to fight.
        Reference(1, 47),       // He puts down the bow and sits, and the teaching begins.
        // Chapter 2
        Reference(2, 7),        // Arjuna surrenders: I am your student, instruct me.
        Reference(2, 11),       // Krishna's first word: you grieve for what needs no grief.
        Reference(2, 13),       // As the body passes through childhood, youth and age.
        Reference(2, 14),       // Heat and cold, pleasure and pain — endure them.
        Reference(2, 20),       // The self is neither born nor does it die.
        Reference(2, 22),       // As a person sheds worn-out garments.
        Reference(2, 23),       // Weapons cannot cut it, fire cannot burn it.
        Reference(2, 47),       // A right to the action alone, never to its fruits.
        Reference(2, 48),       // Evenness of mind is what yoga means.
        Reference(2, 50),       // Yoga is skill in action.
        Reference(2, 62),       // From dwelling on objects, attachment; from attachment, desire.
        Reference(2, 63),       // From anger, delusion; from delusion, ruin.
        Reference(2, 69),       // What is night for all beings is waking for the disciplined.
        // Chapter 3
        Reference(3, 9),        // Work done as sacrifice does not bind.
        Reference(3, 21),       // What a great person does, the world follows.
        Reference(3, 27),       // Nature acts, and the ego thinks itself the doer.
        Reference(3, 35),       // One's own duty imperfectly, over another's done well.
        // Chapter 4
        Reference(4, 7),        // Whenever righteousness declines, I make myself manifest.
        Reference(4, 8),        // To protect the good, and to re-establish dharma.
        Reference(4, 13),       // The four orders were made by me, by quality and by work.
        Reference(4, 24),       // Brahman the offering, Brahman the oblation — said before meals.
        Reference(4, 34),       // Learn by approaching a teacher, by asking, by service.
        Reference(4, 38),       // Nothing in this world purifies like knowledge.
        // Chapter 5
        Reference(5, 10),       // Work offered to Brahman, untouched as a lotus leaf by water.
        Reference(5, 18),       // The learned see the same in a brahmin, a cow, an elephant, a dog.
        Reference(5, 22),       // Pleasures born of contact have a beginning and an end.
        // Chapter 6
        Reference(6, 5),        // Lift yourself by yourself; do not let yourself sink.
        Reference(6, 6),        // The conquered self is a friend; the unconquered, an enemy.
        Reference(6, 19),       // As a lamp in a windless place does not flicker.
        Reference(6, 26),       // Wherever the restless mind wanders, bring it back.
        Reference(6, 34),       // The mind is restless, turbulent, obstinate and strong.
        Reference(6, 35),       // By practice and by dispassion it is held.
        // Chapter 7
        Reference(7, 7),        // Nothing higher than me; all this strung on me like pearls.
        Reference(7, 14),       // This divine maya is hard to cross — but those who come to me cross it.
        Reference(7, 16),       // Four kinds of people come to me, and all of them are good.
        // Chapter 8
        Reference(8, 5),        // Whoever remembers me at the end comes to my being.
        Reference(8, 6),        // Whatever state one dwells on at the end, that state one reaches.
        Reference(8, 16),       // All worlds return, up to Brahma's own; but not those who reach me.
        // Chapter 9
        Reference(9, 22),       // What they lack I bring, what they have I keep.
        Reference(9, 26),       // A leaf, a flower, a fruit, water — offered with love.
        Reference(9, 27),       // Whatever you do, offer it as done to me.
        Reference(9, 29),       // I am the same in all beings; none is hateful, none dear.
        Reference(9, 34),       // Fix your mind on me — said once here and again at the end.
        // Chapter 10
        Reference(10, 8),       // I am the source of everything; from me it all proceeds.
        Reference(10, 10),      // To those constantly devoted I give the yoga of understanding.
        Reference(10, 20),      // I am the self seated in the heart of every being.
        Reference(10, 41),      // Whatever is glorious sprang from a spark of my splendour.
        // Chapter 11
        Reference(11, 12),      // If a thousand suns rose at once in the sky.
        Reference(11, 32),      // I am Time, grown old, come to destroy the worlds.
        Reference(11, 33),      // Rise, then, and win glory — they are already slain.
        Reference(11, 55),      // Who works for me, holds me highest, and is free of enmity.
        // Chapter 12
        Reference(12, 2),       // Those who fix their mind on me are the most devoted.
        Reference(12, 12),      // Better than practice is knowledge, than knowledge meditation.
        Reference(12, 13),      // Hating no creature, friendly and compassionate.
        Reference(12, 15),      // Who troubles no one and is troubled by no one.
        // Chapter 13
        Reference(13, 2),       // This body is called the field; who knows it, the knower of the field.
        // Every number in this chapter runs one ahead of the one these verses
        // are usually quoted under: the corpus is the IIT Kanpur Supersite
        // text, which counts Arjuna's question as 13.1. So 13.17 here is the
        // 13.16 people cite, 13.28 is 13.27, and 13.29 is 13.28. All three are
        // wanted, and the line is what matters, not the number — an earlier
        // note read "13.17 and 13.29, not 13.16 and 13.28", which explained
        // two of the three and appeared to argue against the one between them.
        Reference(13, 17),      // Undivided, yet seeming divided among beings.
        Reference(13, 28),      // The same Lord standing equally in all beings.
        Reference(13, 29),      // Seeing him equally everywhere, one does no harm.
        // Chapter 14
        Reference(14, 5),       // Goodness, passion and darkness — the three born of nature.
        Reference(14, 18),      // Those in goodness rise, those in passion stay, those in darkness sink.
        Reference(14, 26),      // Who serves me with unswerving devotion passes beyond the qualities.
        // Chapter 15
        Reference(15, 1),       // The eternal asvattha, roots above and branches below.
        Reference(15, 7),       // A fragment of my own self becomes the living soul.
        Reference(15, 15),      // I am seated in the heart of all; from me, memory and knowledge.
        // Chapter 16
        Reference(16, 1),       // Fearlessness, purity of heart, steadfastness in knowledge.
        Reference(16, 21),      // Three gates to ruin: desire, anger and greed.
        Reference(16, 24),      // Let scripture be your measure in deciding what to do.
        // Chapter 17
        Reference(17, 3),       // Faith follows one's own nature; a person is made of faith.
        Reference(17, 15),      // Speech that does not distress, that is true, kind and useful.
        Reference(17, 23),      // Om Tat Sat — the threefold designation of Brahman.
        // Chapter 18
        Reference(18, 46),      // By worshipping him through one's own work, a person is fulfilled.
        Reference(18, 61),      // The Lord dwells in the heart of every being.
        Reference(18, 63),      // I have told you; now do as you wish.
        Reference(18, 65),      // Fix your mind on me, be devoted to me, bow to me.
        Reference(18, 66),      // Abandon all dharmas and come to me alone; do not grieve.
        Reference(18, 78),      // Where Krishna is and Arjuna is, there is victory.
    ]

    /// Whether a verse is one of them.
    static func contains(chapter: Int, sutra: Int) -> Bool {
        all.contains(Reference(chapter, sutra))
    }

    /// A chapter and verse number, and nothing else.
    struct Reference: Hashable, Sendable {
        let chapter: Int
        let sutra: Int

        init(_ chapter: Int, _ sutra: Int) {
            self.chapter = chapter
            self.sutra = sutra
        }
    }
}

extension Verse {
    /// Whether this is one of the verses most people arrive already knowing.
    var isFamous: Bool { FamousVerses.contains(chapter: chapter, sutra: sutra) }
}
