//
//  Verse.swift
//  Gita
//

import Foundation
import GRDB

/// One word of the shloka and its meaning.
struct WordMeaning: Identifiable, Hashable, Codable, Sendable {
    /// The word itself — Devanagari in the Hindi list, IAST in the English one.
    let w: String
    /// Its gloss in that list's language.
    let m: String

    var id: String { w }
}

/// One verse of the Gita, as stored in the bundled read-only `gita.sqlite`.
///
/// The Sanskrit comes from srimad.csv. Everything else is generated by
/// `tools/enrich.py` and is **optional** — only part of the corpus has been
/// enriched so far, so every field below `sanskrit` can be nil and the UI has to
/// cope with that rather than assume it is there.
struct Verse: Identifiable, Hashable, Codable, Sendable, FetchableRecord, TableRecord {
    static let databaseTableName = "verses"

    /// Columns are snake_case in SQLite, properties are camelCase in Swift.
    static let databaseColumnDecodingStrategy = DatabaseColumnDecodingStrategy.convertFromSnakeCase

    /// Global running position, 1...701. Matches `counter` in srimad.csv.
    let id: Int
    let chapter: Int
    /// Verse number within its chapter.
    let sutra: Int
    /// Mula shloka in Devanagari.
    let sanskrit: String

    let transliteration: String?
    let hindiTranslation: String?
    let englishTranslation: String?
    let hindiMeaning: String?
    let englishMeaning: String?
    /// JSON as stored; decoded through `words(for:)`.
    let wordByWordHindi: String?
    let wordByWordEnglish: String?

    /// Traditional reference, e.g. "2.47".
    var reference: String { "\(chapter).\(sutra)" }

    /// True once this verse has been through the enrichment pipeline.
    var isEnriched: Bool { transliteration?.isEmpty == false }

    /// Everything the enrichment pipeline produces defaults to absent, so a
    /// fixture or preview only states the fields it actually cares about.
    init(
        id: Int,
        chapter: Int,
        sutra: Int,
        sanskrit: String,
        transliteration: String? = nil,
        hindiTranslation: String? = nil,
        englishTranslation: String? = nil,
        hindiMeaning: String? = nil,
        englishMeaning: String? = nil,
        wordByWordHindi: String? = nil,
        wordByWordEnglish: String? = nil
    ) {
        self.id = id
        self.chapter = chapter
        self.sutra = sutra
        self.sanskrit = sanskrit
        self.transliteration = transliteration
        self.hindiTranslation = hindiTranslation
        self.englishTranslation = englishTranslation
        self.hindiMeaning = hindiMeaning
        self.englishMeaning = englishMeaning
        self.wordByWordHindi = wordByWordHindi
        self.wordByWordEnglish = wordByWordEnglish
    }
}

extension Verse {
    /// Word-by-word meanings in the requested language, or empty if this verse
    /// has not been enriched (or the JSON is somehow unreadable — a malformed
    /// row should show nothing, never crash the reader).
    func words(for language: ReadingLanguage) -> [WordMeaning] {
        let json = language == .sanskrit ? wordByWordHindi : wordByWordEnglish
        guard let data = json?.data(using: .utf8), !data.isEmpty else { return [] }
        return (try? JSONDecoder().decode([WordMeaning].self, from: data)) ?? []
    }

    /// The shloka itself in the requested language: Devanagari, or the IAST
    /// transliteration once it exists.
    func scripture(for language: ReadingLanguage) -> String {
        switch language {
        case .sanskrit: sanskrit
        case .english: transliteration ?? sanskrit
        }
    }
}

extension Verse {
    /// The shloka as stored: one line per line, no punctuation.
    ///
    /// `tools/build_db.py` strips every danda and the trailing verse marker and
    /// joins the lines with "\n" — the same shape RigVeda stores. Nothing here
    /// has to parse punctuation any more; the danda is added back when drawing.
    var lines: [String] { Verse.lines(of: sanskrit) }

    static func lines(of scripture: String) -> [String] {
        scripture
            .split(separator: "\n")
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
    }

    /// The verse ready to draw: each line closed with a danda, in either script.
    ///
    /// A danda is punctuation, so it is applied at render time and applies
    /// equally to the Devanagari and the IAST. The convention: a single danda
    /// closes each line, a double danda closes the verse, and a speaker
    /// attribution ("… उवाच" / "… uvāca") takes none at all.
    func displayLines(for language: ReadingLanguage) -> [String] {
        let raw = Verse.lines(of: scripture(for: language))
        guard let last = raw.indices.last else { return [] }

        return raw.enumerated().map { index, line in
            if Verse.isSpeaker(line) { return line }
            return line + (index == last ? "॥" : "।")
        }
    }

    /// True for a speaker attribution line, in either script.
    static func isSpeaker(_ line: String) -> Bool {
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        return trimmed.hasSuffix("उवाच") || trimmed.lowercased().hasSuffix("uvāca")
    }

    /// Prose translation of the verse in the reading language, if enriched.
    func translation(for language: ReadingLanguage) -> String? {
        let text = language == .sanskrit ? hindiTranslation : englishTranslation
        return (text?.isEmpty == false) ? text : nil
    }

    /// Explanation of the verse in the reading language, if enriched.
    func meaning(for language: ReadingLanguage) -> String? {
        let text = language == .sanskrit ? hindiMeaning : englishMeaning
        return (text?.isEmpty == false) ? text : nil
    }
}
