//
//  Verse.swift
//  Gita
//

import Foundation
import GRDB

/// One word of the shloka and its meaning.
struct WordMeaning: Identifiable, Hashable, Codable, Sendable {
    /// The word itself — Devanagari in the Hindi list, IAST in the English one.
    let w: String
    /// Its gloss in that list's language.
    let m: String

    var id: String { w }
}

/// One verse of the Gita, as stored in the bundled read-only `gita.sqlite`.
///
/// The Sanskrit comes from srimad.csv. Everything else is generated by
/// `tools/enrich.py` and is **optional** — only part of the corpus has been
/// enriched so far, so every field below `sanskrit` can be nil and the UI has to
/// cope with that rather than assume it is there.
struct Verse: Identifiable, Hashable, Codable, Sendable, FetchableRecord, TableRecord {
    static let databaseTableName = "verses"

    /// Columns are snake_case in SQLite, properties are camelCase in Swift.
    static let databaseColumnDecodingStrategy = DatabaseColumnDecodingStrategy.convertFromSnakeCase

    /// Global running position, 1...701. Matches `counter` in srimad.csv.
    let id: Int
    let chapter: Int
    /// Verse number within its chapter.
    let sutra: Int
    /// Mula shloka in Devanagari.
    let sanskrit: String

    let transliteration: String?
    let hindiTranslation: String?
    let englishTranslation: String?
    let hindiMeaning: String?
    let englishMeaning: String?
    /// JSON as stored; decoded through `words(for:)`.
    let wordByWordHindi: String?
    let wordByWordEnglish: String?

    /// Traditional reference, e.g. "2.47".
    var reference: String { "\(chapter).\(sutra)" }

    /// True once this verse has been through the enrichment pipeline.
    var isEnriched: Bool { transliteration?.isEmpty == false }

    /// Everything the enrichment pipeline produces defaults to absent, so a
    /// fixture or preview only states the fields it actually cares about.
    init(
        id: Int,
        chapter: Int,
        sutra: Int,
        sanskrit: String,
        transliteration: String? = nil,
        hindiTranslation: String? = nil,
        englishTranslation: String? = nil,
        hindiMeaning: String? = nil,
        englishMeaning: String? = nil,
        wordByWordHindi: String? = nil,
        wordByWordEnglish: String? = nil
    ) {
        self.id = id
        self.chapter = chapter
        self.sutra = sutra
        self.sanskrit = sanskrit
        self.transliteration = transliteration
        self.hindiTranslation = hindiTranslation
        self.englishTranslation = englishTranslation
        self.hindiMeaning = hindiMeaning
        self.englishMeaning = englishMeaning
        self.wordByWordHindi = wordByWordHindi
        self.wordByWordEnglish = wordByWordEnglish
    }
}

extension Verse {
    /// Word-by-word meanings in the requested language, or empty if this verse
    /// has not been enriched (or the JSON is somehow unreadable — a malformed
    /// row should show nothing, never crash the reader).
    func words(for language: ReadingLanguage) -> [WordMeaning] {
        let json = language == .sanskrit ? wordByWordHindi : wordByWordEnglish
        guard let data = json?.data(using: .utf8), !data.isEmpty else { return [] }
        return (try? JSONDecoder().decode([WordMeaning].self, from: data)) ?? []
    }

    /// The shloka itself in the requested language: Devanagari, or the IAST
    /// transliteration once it exists.
    func scripture(for language: ReadingLanguage) -> String {
        switch language {
        case .sanskrit: sanskrit
        case .english: transliteration ?? sanskrit
        }
    }
}

extension Verse {
    /// The shloka broken into display lines.
    ///
    /// Only 11 of the 701 rows in srimad.csv actually contain newlines; the rest
    /// are a single run of text in which the danda (।) is the only line break
    /// available. So: honour real newlines where they exist, and otherwise break
    /// on the danda — keeping the trailing `।।chapter.verse।।` marker attached to
    /// the final line, where it belongs.
    var lines: [String] { Verse.lines(of: sanskrit) }

    /// The same breaking applied to any scripture text, so the IAST
    /// transliteration lays out on the same lines as the Devanagari.
    static func lines(of scripture: String) -> [String] {
        let text = scripture.trimmingCharacters(in: .whitespacesAndNewlines)

        if text.contains("\n") {
            return text
                .split(separator: "\n")
                .map { $0.trimmingCharacters(in: .whitespaces) }
                .filter { !$0.isEmpty }
        }

        var body = text
        var marker = ""
        if let range = body.range(of: "।।[0-9]+\\.[0-9]+।।$", options: .regularExpression) {
            marker = String(body[range])
            body = String(body[body.startIndex ..< range.lowerBound])
        }

        // Devanagari marks the break with a danda; IAST transliteration uses a
        // full stop for the same thing. Whichever this text uses is the break.
        let danda = body.contains("।") ? "।" : "."
        var result = body
            .components(separatedBy: danda)
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
            .map { $0 + danda }

        if !marker.isEmpty {
            if result.isEmpty {
                result = [marker]
            } else {
                result[result.count - 1] = String(result[result.count - 1].dropLast()) + marker
            }
        }
        return result
    }
}
