//
//  DevanagariSearchTests.swift
//  GitaTests
//

import Foundation
import Testing
@testable import Gita

/// Searching in the script the book is written in.
///
/// Half of this app's readers will type Devanagari, and nothing pinned that it
/// works. It does — `verses_fts` indexes `sanskrit`, `hindi_translation` and
/// `hindi_meaning` alongside the English columns — but "it does" is a fact
/// about today's schema, and the schema is generated by `tools/build_db.py`.
/// Drop a column from that list and English search still passes every test in
/// the suite while Hindi quietly returns nothing.
///
/// So this pins the columns from the outside, by asking questions only each one
/// can answer, and pins the sanitiser's treatment of a script whose words carry
/// combining marks that a naive filter would strip.
@Suite("Devanagari search")
struct DevanagariSearchTests {

    private func database() throws -> ContentDatabase { try ContentDatabase() }

    // MARK: - The script finds the book

    @Test("Common Devanagari words find verses", arguments: [
        "कर्म",         // action — the word the whole Gita turns on
        "अर्जुन",        // Arjuna, named throughout
        "योग",          // yoga
        "धर्म",          // dharma
        "आत्मा",         // the self
    ])
    func devanagariFindsVerses(term: String) throws {
        let hits = try database().search(term)
        #expect(!hits.isEmpty, "\(term) found nothing")
    }

    /// The reference everyone knows, found by its opening words in the original
    /// script. If Devanagari search regresses to matching nothing, this is the
    /// case that says so in one line.
    @Test("The best-known shloka is found by its own first word")
    func theOpeningOfTwoFortySeven() throws {
        let hits = try database().search("कर्मण्येवाधिकारस्ते")
        #expect(hits.contains { $0.verse.chapter == 2 && $0.verse.sutra == 47 },
                "2.47 was not among the results for its own opening word")
    }

    // MARK: - Each indexed column answers for itself

    /// A word that appears in the **Sanskrit** but not in the Hindi prose.
    @Test("The shloka column is searchable")
    func theShlokaIsIndexed() throws {
        let hits = try database().search("धृतराष्ट्र")
        #expect(hits.contains { $0.verse.chapter == 1 && $0.verse.sutra == 1 },
                "1.1 names Dhritarashtra in its shloka and was not found")
    }

    /// Hindi prose that is **not** in any shloka: if only `sanskrit` were
    /// indexed, this would return nothing.
    @Test("The Hindi translation and meaning are searchable")
    func theHindiProseIsIndexed() throws {
        let hits = try database().search("तुम्हारा अधिकार")
        #expect(!hits.isEmpty, "Hindi prose found nothing — is hindi_translation indexed?")
    }

    // MARK: - Scripts do not collide

    /// The same verse, reachable from either script.
    ///
    /// Not that the two searches return the same *set* — they rank differently
    /// and read different columns — but that neither script is a dead end for a
    /// verse the other can reach.
    @Test("Either script reaches the same verse")
    func bothScriptsReachTheSameVerse() throws {
        let db = try database()
        let devanagari = try db.search("कर्मण्येवाधिकारस्ते")
        let latin = try db.search("karmany")

        let inBoth = { (hits: [SearchHit]) in
            hits.contains { $0.verse.chapter == 2 && $0.verse.sutra == 47 }
        }
        #expect(inBoth(devanagari), "Devanagari did not reach 2.47")
        #expect(inBoth(latin), "transliteration did not reach 2.47")
    }

    /// `remove_diacritics 2` is what lets someone type the transliteration
    /// without reaching for combining marks. It is a tokeniser setting in the
    /// generated schema, so it can be lost the same way a column can.
    @Test("Transliteration is found without its diacritics", arguments: [
        ("krsna", "kṛṣṇa"), ("arjuna", "arjuna"), ("dharmaksetre", "dharmakṣetre"),
    ])
    func diacriticsAreOptional(bare: String, marked: String) throws {
        let db = try database()
        #expect(!(try db.search(bare)).isEmpty, "\(bare) found nothing, for \(marked)")
    }

    // MARK: - The sanitiser leaves the script alone

    /// The one that would break silently.
    ///
    /// `ContentDatabase.sanitize` strips what FTS5 would read as syntax. A
    /// filter written against ASCII — "letters and digits only" — throws away
    /// the matras and virama that Devanagari words are built from, leaving a
    /// query of bare consonants that matches nothing. The words above already
    /// cover it, but this asserts the shape rather than the outcome.
    @Test("Sanitising keeps Devanagari intact", arguments: [
        "कर्म", "अर्जुन", "श्रीमद्भगवद्गीता", "कर्मण्येवाधिकारस्ते",
    ])
    func sanitisingKeepsTheScript(term: String) throws {
        let terms = ContentDatabase.sanitize(term)
        #expect(terms.joined() == term,
                "sanitising changed \(term) into \(terms.joined(separator: " "))")
    }

    /// Mixed scripts in one query must not throw, whatever they return.
    @Test("A query in both scripts is safe", arguments: [
        "कर्म yoga", "arjuna अर्जुन", "2.47 कर्म", "कर्म AND योग",
    ])
    func mixedScriptsAreSafe(query: String) throws {
        _ = try database().search(query)
    }
}
