#!/usr/bin/env python3
"""Compile srimad.csv into the app's bundled, read-only gita.sqlite.

The Sanskrit mula shloka comes from srimad.csv — `counter`, `chapter`, `sutra`
and `mool_shloka`. The CSV's own Hindi and English columns are deliberately NOT
used; every other language field is generated by tools/enrich.py and merged in
from enriched.sqlite when that file exists. Verses that have not been enriched
yet simply carry NULLs, and the app renders without them.

srimad.csv stays the single source of truth, shared with the Hugo site. The
database is a build artifact: regenerate it, never hand-edit it.

    python3 tools/build_db.py [--csv srimad.csv] [--out <path>]
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import re
import tomllib
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CSV = ROOT / "srimad.csv"
ENRICHED_DB = ROOT / "enriched.sqlite"
CHAPTERS_TOML = ROOT / "data" / "chapters.toml"
DEFAULT_OUT = ROOT / "app" / "Gita" / "Gita" / "Resources" / "Database" / "gita.sqlite"

CONTENT_VERSION = 1

SCHEMA = """
CREATE TABLE verses (
    id       INTEGER PRIMARY KEY,   -- global position, == csv `counter`
    chapter  INTEGER NOT NULL,
    sutra    INTEGER NOT NULL,
    sanskrit TEXT    NOT NULL,      -- mula shloka, line breaks preserved

    -- Everything below is generated by tools/enrich.py. NULL until a verse has
    -- been enriched, so the app must treat all of it as optional.
    transliteration      TEXT,      -- IAST
    hindi_translation    TEXT,
    english_translation  TEXT,
    hindi_meaning        TEXT,
    english_meaning      TEXT,
    word_by_word_hindi   TEXT,      -- JSON [{"w":…,"m":…}, …]
    word_by_word_english TEXT       -- JSON [{"w":…,"m":…}, …]
);

CREATE UNIQUE INDEX idx_verses_chapter_sutra ON verses(chapter, sutra);
CREATE INDEX idx_verses_chapter ON verses(chapter);

CREATE VIRTUAL TABLE verses_fts USING fts5(
    sanskrit,
    transliteration,
    hindi_translation,
    english_translation,
    hindi_meaning,
    english_meaning,
    content='verses',
    content_rowid='id',
    tokenize='unicode61 remove_diacritics 2'
);

CREATE TABLE chapters (
    id          INTEGER PRIMARY KEY,   -- 1..18
    name_sa     TEXT NOT NULL,         -- अर्जुनविषादयोग
    name_en     TEXT NOT NULL,         -- "The Despondency of Arjuna"
    verse_count INTEGER NOT NULL
);

CREATE TABLE meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
"""


# The four attributions that open a spoken verse, matched explicitly rather than
# by searching for "उवाच". Sandhi hides that word: "भगवान् + उवाच" becomes
# "भगवानुवाच", where the उ is a combining vowel SIGN (ु) and no substring search
# for "उवाच" can find it — which silently missed all 28 श्री भगवानुवाच verses.
# Matching the known forms also avoids the one false positive, "तमुवाच" in 2.10,
# where उवाच is an ordinary verb mid-verse rather than an attribution.
SPEAKERS = re.compile(
    r"^\s*(श्री\s*भगवानुवाच|भगवानुवाच|धृतराष्ट्र\s*उवाच|सञ्जय\s*उवाच|संजय\s*उवाच|अर्जुन\s*उवाच)"
)
DANDA = re.compile(r"।+")
VERSE_MARKER = re.compile(r"।।\s*[\d.]+\s*।।\s*$")

# The Supersite prints the reference it is quoting above the words themselves,
# and the scrape carried it into the text: "।।1.1।।धृतराष्ट्र बोले…" in the
# Hindi and the commentary, "1.1 Dhritarashtra said…" in the English. It is the
# page's furniture, not the translation, and it appears on nearly every row of
# all three columns.
#
# Two shapes each, and both were found by counting rather than assumed: a range
# is written with a hyphen as often as with spaces ("।।8.1 -- 8.2।।"), and the
# English number carries a trailing dot on 46 rows and none on the other 609.
REFERENCE = re.compile(
    r"^\s*(?:।+\s*[\d.\s\-–—]+।+|॥+\s*[\d.\s\-–—]+॥+|\d+\.\d+\.?)\s*"
)


def strip_reference(text: str) -> str:
    """Drop the leading "।।2.47।。" / "2.47" the scrape prefixes to a translation.

    Applied to the scraped prose only. The enriched columns never carried it.

    The danda runs are `+` rather than exactly one or two: 10.9 closes its
    marker with three, "।।10.9।।।", and matching a fixed pair left the stray one
    at the head of the sentence.
    """
    return REFERENCE.sub("", text or "", count=1).strip()


def normalize(text: str) -> str:
    """Turn the raw shloka into newline-separated lines with no dandas.

    The source mixes three conventions: a few rows use real newlines, most use
    the danda (।) as the only break, and nearly all end with a ।।chapter.verse।।
    marker. Storing that variety means every consumer has to re-parse it.

    So the stored form is the same shape RigVeda uses — one line per line, "\n"
    as the terminator, no danda anywhere. The danda is punctuation and belongs to
    presentation; the reader adds it back when drawing the verse.
    """
    text = text.replace("\r\n", "\n").replace("\r", "\n").strip()
    text = VERSE_MARKER.sub("", text)

    lines: list[str] = []
    for chunk in text.split("\n"):
        for segment in DANDA.split(chunk):
            segment = segment.strip()
            if segment:
                lines.append(segment)

    # "सञ्जय उवाचदृष्ट्वा तु…" — the attribution is usually run straight into the
    # first word of the verse. Give it its own line.
    if lines:
        match = SPEAKERS.match(lines[0])
        if match:
            speaker = match.group(1).strip()
            rest = lines[0][match.end():].strip()
            lines[:1] = [speaker, rest] if rest else [speaker]

    return "\n".join(lines)


def read_verses(csv_path: Path) -> list[tuple[int, int, int, str]]:
    with csv_path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))

    required = {"counter", "chapter", "sutra", "mool_shloka"}
    missing = required - set(rows[0] if rows else {})
    if missing:
        sys.exit(f"error: {csv_path} is missing column(s): {', '.join(sorted(missing))}")

    verses = []
    for line_no, row in enumerate(rows, start=2):
        shloka = normalize(row["mool_shloka"] or "")
        if not shloka:
            sys.exit(f"error: empty mool_shloka at {csv_path}:{line_no}")
        verses.append(
            (int(row["counter"]), int(row["chapter"]), int(row["sutra"]), shloka)
        )

    verses.sort(key=lambda v: (v[1], v[2]))
    return verses


ENRICHED_FIELDS = [
    "transliteration", "hindi_translation", "english_translation",
    "hindi_meaning", "english_meaning", "word_by_word_hindi", "word_by_word_english",
]


def align_transliteration(sanskrit: str, translit: str | None) -> str | None:
    """Make the IAST lay out on the same lines as the Devanagari.

    The model is asked to mirror the shloka's line structure and mostly does,
    but two deviations recur across the corpus:

    * a literal backslash-n instead of a newline (the escape survives the JSON
      round trip as two characters);
    * splitting each half-line into its two padas, so four lines where the
      Devanagari has two.

    Both are mechanical, so they are repaired here rather than by re-running the
    model. Anything that is not an exact multiple is left alone — better an
    honest mismatch than a guess at where a line belongs.
    """
    if not translit:
        return translit

    translit = translit.replace("\\n", "\n")
    source = [l for l in sanskrit.split("\n") if l.strip()]
    target = [l.strip() for l in translit.split("\n") if l.strip()]
    if len(source) == len(target):
        return "\n".join(target)

    # Keep an attribution line paired with its counterpart, then align the body.
    head = 1 if SPEAKERS.match(source[0]) and len(target) > len(source) else 0
    body_source, body_target = source[head:], target[head:]
    if body_source and body_target and len(body_target) % len(body_source) == 0:
        factor = len(body_target) // len(body_source)
        if factor > 1:
            merged = [" ".join(body_target[i * factor:(i + 1) * factor])
                      for i in range(len(body_source))]
            return "\n".join(target[:head] + merged)

    return "\n".join(target)


def read_enrichment() -> dict[tuple[int, int], tuple]:
    """Enriched columns keyed by (chapter, sutra). Empty if never generated."""
    if not ENRICHED_DB.exists():
        return {}
    db = sqlite3.connect(f"file:{ENRICHED_DB}?mode=ro", uri=True)
    try:
        rows = db.execute(
            f"SELECT chapter, sutra, {', '.join(ENRICHED_FIELDS)} FROM enriched_verses"
        ).fetchall()
    except sqlite3.OperationalError:
        return {}
    finally:
        db.close()
    return {(row[0], row[1]): row[2:] for row in rows}


def read_chapters() -> dict[int, tuple[str, str]]:
    """Chapter names from data/chapters.toml — the same file the website uses."""
    if not CHAPTERS_TOML.exists():
        sys.exit(f"error: {CHAPTERS_TOML} not found")
    with CHAPTERS_TOML.open("rb") as handle:
        data = tomllib.load(handle)
    return {int(k): (v["sa"], v["en"]) for k, v in data.items()}


def build(csv_path: Path, out_path: Path) -> None:
    verses = read_verses(csv_path)
    enrichment = read_enrichment()
    chapters = read_chapters()
    checksum = hashlib.sha256(csv_path.read_bytes()).hexdigest()

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.unlink(missing_ok=True)

    db = sqlite3.connect(out_path)
    try:
        db.executescript(SCHEMA)
        blank = (None,) * len(ENRICHED_FIELDS)

        def align(sanskrit: str, extra: tuple) -> tuple:
            index = ENRICHED_FIELDS.index("transliteration")
            return extra[:index] + (align_transliteration(sanskrit, extra[index]),) + extra[index + 1:]

        db.executemany(
            f"""INSERT INTO verses (id, chapter, sutra, sanskrit, {', '.join(ENRICHED_FIELDS)})
                VALUES ({', '.join('?' * (4 + len(ENRICHED_FIELDS)))})""",
            [v + align(v[3], enrichment.get((v[1], v[2]), blank)) for v in verses],
        )
        counts: dict[int, int] = {}
        for verse in verses:
            counts[verse[1]] = counts.get(verse[1], 0) + 1
        missing = set(counts) - set(chapters)
        if missing:
            sys.exit(f"error: chapters.toml has no entry for {sorted(missing)}")
        db.executemany(
            "INSERT INTO chapters (id, name_sa, name_en, verse_count) VALUES (?, ?, ?, ?)",
            [(n, chapters[n][0], chapters[n][1], counts[n]) for n in sorted(counts)],
        )

        db.execute("INSERT INTO verses_fts(verses_fts) VALUES ('rebuild')")
        db.executemany(
            "INSERT INTO meta (key, value) VALUES (?, ?)",
            [
                ("content_version", str(CONTENT_VERSION)),
                ("built_at", datetime.now(timezone.utc).isoformat(timespec="seconds")),
                ("source_checksum", checksum),
                ("source_file", csv_path.name),
                ("verse_count", str(len(verses))),
                ("columns", "counter,chapter,sutra,mool_shloka"),
                ("enriched_count", str(len(enrichment))),
            ],
        )
        db.commit()
        db.execute("PRAGMA optimize")
        db.execute("VACUUM")
    finally:
        db.close()

    chapters = sorted({v[1] for v in verses})
    size_kb = out_path.stat().st_size / 1024
    print(f"wrote {out_path.relative_to(ROOT)}  ({size_kb:.0f} KB)")
    print(f"  {len(verses)} verses across {len(chapters)} chapters ({chapters[0]}–{chapters[-1]})")
    if enrichment:
        print(f"  {len(enrichment)} enriched from {ENRICHED_DB.name}; the rest carry NULLs")
    else:
        print(f"  no {ENRICHED_DB.name} found — Sanskrit only")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    if not args.csv.exists():
        sys.exit(f"error: {args.csv} not found")
    build(args.csv, args.out)


if __name__ == "__main__":
    main()
